---
title: "Example"
author: "Christian Escoto"
date: "2025-04-17"
output: pdf_document
---

Libraries
```{r setup, include=FALSE}
library(viridis)
library(ggplot2)
library(dplyr)
```

Prepare training data and test data
```{r Training and test}
#create a copy to work
Neo22.1<-Neo22

#Eliminate unnecessary
Neo22.1$Location<-NULL
Neo22.1$Unit<-NULL
Neo22.1$germplasmDbId<-NULL

# Divide data into training and test
set.seed(123)
indices <- sample(1:nrow(Neo22.1), size = 0.5*nrow(Neo22.1))
train_data <- Neo22.1[indices, ]
test_data <- Neo22.1[-indices, ]

```

The functions have the same syntaxis:
Function.name(train_data, test_data, "target_feature")
```{r Predictions}
#Mboost
mboost<-mboost_model(train_data, test_data, "Grain.yield")

mboost$predictions

mboost$RMSE

mboost$correlation

#Random forest
rf<-rf_model(train_data, test_data, "Grain.yield")

rf$predictions

rf$RMSE

rf$correlation

#Xgboost
xgb<-xgb_model(train_data, test_data, "Grain.yield")

xgb$predictions

xgb$RMSE

xgb$correlation

#Catboost
cat<-cat_model(train_data, test_data, "Grain.yield")

cat$predictions

cat$RMSE

cat$correlation

#PCR
pcr<-pcr_model(train_data, test_data, "Grain.yield")

pcr$predictions

pcr$RMSE

pcr$correlation

#Gradient boosting (don't run it if you have hurry)
gbm<-gbm_model(train_data, test_data, "Grain.yield")

gbm$predictions

gbm$RMSE

gbm$correlation

#Bayes A
bayesA<-bayesA_model(train_data, test_data, "Grain.yield")

bayesA$predictions

bayesA$RMSE

bayesA$correlation

#Bayes Lasso
bayesL<-bayesL_model(train_data, test_data, "Grain.yield")

bayesL$predictions

bayesL$RMSE

bayesL$correlation

#Bayes Ridge
bayesR<-bayesR_model(train_data, test_data, "Grain.yield")

bayesR$predictions

bayesR$RMSE

bayesR$correlation

#Lineal model
#Lasso
LL<-lineal_model(train_data, test_data, "Grain.yield", alpha_value = 1)

#Elastinet
LE<-lineal_model(train_data, test_data, "Grain.yield", alpha_value = 0.5)

#Ridge
LR<-lineal_model(train_data, test_data, "Grain.yield", alpha_value = 0)

```

Data visualization 
```{r}
compare_predictions("Xgboost"=xgb$predictions, "Random Forest"=rf$prediction, "Mboost"=mboost$predictions, "Observed" = test_data$Grain.yield)
```

